version: '3'

networks:
    blah2:
      external: true

services:

  blah2:
    restart: always
    build: .
    image: blah2
    tty: true
    depends_on: 
      - blah2_api
    volumes:
      - ./config:/blah2/config
      - /opt/blah2/save:/blah2/save
      - /dev/shm:/dev/shm:rw
      - /dev/usb:/dev/usb:rw
    network_mode: host
    privileged: true
    command: "/blah2/bin/blah2 -c config/config.yml"
    container_name: blah2

  blah2_web:
    restart: always
    image: httpd:2.4
    ports: 
      - 49152:80
    volumes:
      - ./html:/usr/local/apache2/htdocs
    networks:
      - blah2
    container_name: blah2-web

  blah2_api:
    restart: always
    build: ./api
    image: blah2_api
    volumes:
      - ./config:/usr/src/app/config
    network_mode: host
    command: "node server.js /usr/src/app/config/config.yml"
    container_name: blah2-api
