version: '3'

networks:
    nginx-web:
      external: true

services:

  blah2:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ~/blah2/replay:/blah2/replay
      - ./config:/blah2/config
    network_mode: host
    privileged: true
    command: /blah2/bin/blah2 -c config/config.yml
    container_name: blah2

  blah2_frontend:
    restart: always
    image: httpd:2.4
    ports: 
      - 49152:80
    volumes:
      - ./html:/usr/local/apache2/htdocs
    networks:
      - nginx-web
    container_name: blah2-web

  blah2_api:
    restart: always
    build: ./api
    ports:
      - 3000:8080
    network_mode: host
    container_name: blah2-api
