FROM nginx:alpine
LABEL maintainer="OffWorld Lab"
LABEL org.opencontainers.image.source https://github.com/offworldlabs/blah2-arm

COPY nginx.conf /etc/nginx/nginx.conf
COPY html/ /usr/local/apache2/htdocs/