capture:
  fs: 2000000
  fc: 204640000
  type: "RspDuo"
  replay:
    state: false
    loop: true
    file: '/opt/blah2/replay/file.rspduo'

process:
  data:
    cpi: 0.5
    buffer: 1.5
    overlap: 0
  ambiguity:
    delayMin: -10
    delayMax: 300
    dopplerMin: -250
    dopplerMax: 250
  clutter:
    delayMin: -10
    delayMax: 300
  detection:
    pfa: 0.00001
    nGuard: 2
    nTrain: 6
    minDelay: 5
    minDoppler: 15
    nCentroid: 6

network:
  ip: 0.0.0.0
  ports:
    api: 3000
    map: 3001
    detection: 3002
    timestamp: 4000
    timing: 4001
    iqdata: 4002

save:
  iq: true
  map: false
  detection: false
  timing: false
  path: "/blah2/save/"
