capture:
  fs: 2000000
  fc: 204640000
  type: "RspDuo"
  replay:
    state: false
    loop: true
    file: '/opt/blah2/replay/file.rspduo'

process:
  data:
    cpi: 1
    buffer: 1.5
    overlap: 0
  ambiguity:
    delayMin: -10
    delayMax: 300
    dopplerMin: -300
    dopplerMax: 300
  clutter:
    delayMin: -10
    delayMax: 300
  detection:
    pfa: 0.000001
    nGuard: 10
    nTrain: 20

network:
  ip: 0.0.0.0
  ports:
    api: 3000
    map: 3001
    detection: 3002

save:
  iq: true
  map: true
  detection: false
  path: "/opt/blah2/"
